// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt8yNqLkpVNEQQw-paAUK2V7wlEYwulqM',
    appId: '1:1049403585831:web:98e2840ed897aed66ea502',
    messagingSenderId: '1049403585831',
    projectId: 'note291-85279',
    authDomain: 'note291-85279.firebaseapp.com',
    storageBucket: 'note291-85279.firebasestorage.app',
    measurementId: 'G-ZWK12HTNWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLhY03ARjmTmcJBwOxm2gYn3d1KFJN6bY',
    appId: '1:1049403585831:android:82391c7f7fc325656ea502',
    messagingSenderId: '1049403585831',
    projectId: 'note291-85279',
    storageBucket: 'note291-85279.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAJ5MiGWO2onUa2sCiCfb3qf3y33VCx04',
    appId: '1:1049403585831:ios:dcc2a512c7bf32c06ea502',
    messagingSenderId: '1049403585831',
    projectId: 'note291-85279',
    storageBucket: 'note291-85279.firebasestorage.app',
    iosBundleId: 'com.example.firebase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAJ5MiGWO2onUa2sCiCfb3qf3y33VCx04',
    appId: '1:1049403585831:ios:dcc2a512c7bf32c06ea502',
    messagingSenderId: '1049403585831',
    projectId: 'note291-85279',
    storageBucket: 'note291-85279.firebasestorage.app',
    iosBundleId: 'com.example.firebase1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt8yNqLkpVNEQQw-paAUK2V7wlEYwulqM',
    appId: '1:1049403585831:web:9c425d438ec5ea9b6ea502',
    messagingSenderId: '1049403585831',
    projectId: 'note291-85279',
    authDomain: 'note291-85279.firebaseapp.com',
    storageBucket: 'note291-85279.firebasestorage.app',
    measurementId: 'G-WM03H4CP2C',
  );
}
